### ISSUE TITLE
Example Project / Adding Dockerfiles

### ISSUE THREAD

**Issue by jasperf** [nickjj/ansible-docker#21]
Really love what you did. Was looking for something like this. 

What I miss though is an example project where you have the Ansible root and so on setup. 

Also, I miss the role or mention in the README to add the Docker files and or directories to the online host. When you provision the Dockerfiles really should be part of it. The application you can deploy using deployer or another playbook, but for this provision package the role to add your Docker setup would be really useful.

Perhaps with something like `ansible/roles/site_name/tasks/main.yml` :

```yaml
---  
  - name: Create Docker base directory    
    file: path={{ work_dir }} state=directory
 
  - name: Copy docker-compose file    
    template: src=docker-compose.j2 dest={{ work_dir }}/docker-compose.yml

  - name: Setup ufw
    ufw: rule=allow port=80 proto=tcp

  - name: Open up SSL ufw    
    ufw: rule=allow port=443 proto=tcp

  - name: create the logrotate conf for docker    
    copy: src=logrotate_docker dest=/etc/logrotate.d/docker

  - name: copy the backup script    
    copy: src=site-backup dest={{ work_dir }}/site-backup mode=755    
    tags:  
    - prod
  
  - name: install s3cmd    
    apt: name=s3cmd state=present update_cache=yes    
    tags: 
    - prod

  - name: install s3cfg    
    template: src=s3cfg dest=/root/.s3cfg    
    tags:  
    - prod

  - name: schedule backup to run weekly    
    cron: name="site backup" minute="0" hour="2" weekday="1" job="{{ work_dir }}/site-backup" user="root"    
    tags:      
    - prod   

  - name: Copy over site-upgrade    
    copy: src=site-upgrade dest={{ work_dir }}/ mode=755 
  
  - name: Copy over site-normal    
    copy: src=site-normal dest={{ work_dir }}/ mode=755
--
```

and

```yaml
---
  - name: Create {{ service }} directory
    file: path={{ work_dir }} state=directory owner=root group=root 
 
  - name: Load {{ service }}
    synchronize: src={{ service }} dest={{ work_dir }} group=no owner=no rsync_path='sudo rsync'
 
  - name: Make files executable
    file: path={{ work_dir }}/{{ service }}/{{ item }} mode=755
    with_items:
```

as mentioned at https://ejosh.co/de/2015/05/ansible-for-server-provisioning/ and repo https://github.com/johanan/Ansible-and-Docker
