### ISSUE TITLE
variables have no effect

### ISSUE THREAD

**Issue by atkinsj** [nickjj/ansible-docker#36]
Running v1.1.0:

`- nickjj.docker, v1.1.0`

with this configuration:

```
- hosts: all
  become: True
  roles:
      - common
      - { role: "nickjj.docker", tags: "docker" }
  vars:
    docker__daemon_options: "\"dns\": [\"{{ dns_servers | join('\", \"')}}\"]"
    docker__registries:
      - registry_url: "redacted"
        username: "redacted"
        password: "redacted"
        state: present
````

but if I cat `/etc/docker/daemon.json`:

```
{  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "1000"
  }
}
```

and the registry is not logged in either.

Any idea how else to debug this?
