### ISSUE TITLE
How to use docker__users?

### ISSUE THREAD

**Issue by benyanke** [nickjj/ansible-docker#38]
I'm having trouble using `docker__users`. I've tried a number of methods, and the most promising so far has been:

```yml
- hosts: dockerhosts
  roles:
    - name: "Docker Install and Configure"
      tags: ["docker"]
      become: yes
      become_method: sudo
      role: nickjj.docker
      docker__users: ["jdoe", "sdoe"]
```

However, I haven't been able to get any of it working. How do you implement the variables when specifying the role?
