### ISSUE TITLE
Start docker with extra host

### ISSUE THREAD

**Issue by amarandon** [nickjj/ansible-docker#39]
I'm in the process of upgrading this role and I'm struggling to figure out how I can deal with extra hosts. Until now I was using this:
```yaml
docker_daemon_options:
  - "-H 0.0.0.0:4444"
  - "-H fd://"
  - "--tlsverify"
  - "--tlscacert /etc/docker/certs/ca.pem"
  - "--tlscert /etc/docker/certs/server-cert.pem"
  - "--tlskey /etc/docker/certs/server-key.pem"
```
From what I understand, it's no longer possible to add flags to the systemd unit file as all daemon configuration is now done via `docker__daemon_options` which ends up in `/etc/docker/daemon.json`.

The problem is that, as stated by [Docker documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file):

> Note: You cannot set options in daemon.json that have already been set on daemon startup as a flag. On systems that use systemd to start the Docker daemon, -H is already set, so you cannot use the hosts key in daemon.json to add listening addresses. See https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options for how to accomplish this task with a systemd drop-in file.

And indeed, if I try this:
```yaml
docker__daemon_options: |
  "tlsverify": true,
  "tlscacert": "/etc/docker/certs/ca.pem",
  "tlscert": "/etc/docker/certs/server-cert.pem",
  "tlskey": "/etc/docker/certs/server-key.pem",
  "hosts": ["0.0.0.0:4444"]
```
Docker cannot start:
```
unable to configure the Docker daemon with file /etc/docker/daemon.json:
the following directives are specified both as a flag and in the configuration file:
hosts: (from flag: [fd://], from file: [0.0.0.0:4444])
```
As pointed out by Docker documentation, I can overwrite the systemd unit file myself, but from my point of view it seems that there might be a regression in this Ansible role, unless I'm missing something.

Thank you for your time reading my report! Any thoughts on this?
