### ISSUE TITLE
docker_service: Unable to load docker-compose.

### ISSUE THREAD

**Issue by obilodeau** [nickjj/ansible-docker#43]
Error:

```
Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose
```

playbook:
```yaml
  roles:
  # Install most docker_service dependencies
  - { role: "nickjj.docker", tags: ["docker"] }

  tasks:
  - name: test docker-compose
    docker_service:
      project_src: test
```

Stack trace:
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_docker_service_payload_U2NKy6/__main__.py", line 456, in <module>
    from compose import __version__ as compose_version

fatal: [138.xx.xx.183]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": null,
            "dependencies": true,
            "docker_host": "unix://var/run/docker.sock",
            "files": null,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": null,
            "project_src": "../<...>",
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": false,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": false,
            "tls_hostname": "localhost",
            "tls_verify": false
        }
    },
    "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose"
}
```

## Workaround:

Running `pip install docker-compose` on the server managed by ansible fixed the issue.

## Version infos
galaxy info:
```
Role: nickjj.docker
	description: Install Docker and optionally Docker Compose.
	active: True
	commit: d498cc15f393312ae9e104e13cc3ac7d07365c8d
	commit_message: Update README to link to the latest release
	commit_url: https://api.github.com/repos/nickjj/ansible-docker/git/commits/d498cc15f393312ae9e104e13cc3ac7d07365c8d
	company: 
	created: 2016-10-08T23:13:50.040014Z
	dependencies: []
	download_count: 2838
	forks_count: 69
	galaxy_info:
		author: Nick Janetakis
		galaxy_tags: ['containers', 'compose', 'docker', 'packaging', 'system']
		license: MIT
		min_ansible_version: 2.5
		platforms: [{'name': 'Ubuntu', 'versions': ['xenial', 'bionic']}, {'name': 'Debian', 'versions': ['jessie', 'stretch']}]
		role_name: docker
	github_branch: master
	github_repo: ansible-docker
	github_user: nickjj
	id: 12606
	imported: 2018-11-08T21:18:19.792556-05:00
	install_date: Thu Nov 15 16:08:42 2018
	intalled_version: v1.5.0
	is_valid: True
	issue_tracker_url: https://github.com/nickjj/ansible-docker/issues
	license: MIT
	min_ansible_version: 2.5
	modified: 2018-11-09T02:18:19.792718Z
	open_issues_count: 0
	path: ['/home/xxx/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
	role_type: ANS
	stargazers_count: 195
	travis_status_url: 
```

ansible version:
```
ansible --version
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/olivier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

**Comment by nickjj** [comment]
When you run it directly on your host, are you using a virtualenv?

This role won't select a virtualenv when pip installing it.

**Comment by obilodeau** [comment]
I run `ansible-playbook` directly on my machine (arch linux, python3 by default) but the error is when I run a playbook on a server in my inventory (ubuntu 18.04).

Re-reading myself, I said:

> Running `pip install docker-compose` on the host fixed the issue.

I meant guest or server not host. Edited description to fix it.

**Comment by obilodeau** [comment]
Role definition is just:
```yaml
  roles:
  # Install most docker_service dependencies
  - { role: "nickjj.docker", tags: ["docker"] }
```

So I guess compose installed.

I could run the `docker-compose` binary before I did the `pip install`. The `docker-compose` binary is pulled from the web here: https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml#L129

But nothing is pulling docker-compose from pip: https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml#L22

I think `docker_service` relies on it to be installed via pip.

**Comment by nickjj** [comment]
It does require it if you use the compose bits but not everyone using this role uses `docker_service`.

Right now `pip install docker` is happening mainly because `docker_login` requires it.

I'm torn on forcing users to install compose through pip.

**Comment by obilodeau** [comment]
Having the following before the `docker_service` task works as a workaround:

```
  tasks:
  - pip: name=docker-compose
```

To me, this workaround is simple enough so do what you prefer. UX could be better but ideally `docker_service` would make sure its deps are installed on its own. That's the real UX flaw in my opinion.

As a side note, I'm curious, if you are not using `docker_service`, what do you use to manage your compose with ansible?

**Comment by nickjj** [comment]
You could also remove that task and change this task:

```yml
- name: Pip install docker for Ansible's docker_login and docker_service modules
  pip:
    name: "docker"
```

You can change the name to be: `["docker", "docker-compose"]` instead.

Maybe that's a reasonable compromise. One where this role would allow you to configure which pip packages to install, this way if you need compose, you add it, but it defaults to just docker.

I don't manage any containers with Ansible because I don't use Ansible to initiate deploying my web applications. I only use Ansible to get my machines to the point where everything can be ran, but then I use either git hooks or CI services to handle deploying the app, and this is where I set up things like stopping compose, rebuilding, pulling, etc. and bringing it all back up.

**Comment by nickjj** [comment]
You're more than welcome to open a PR on this, but if you do it, please follow the standards on how the rest of this role is laid out in terms of variable naming, ordering, and how it appears in the README.

Although figuring out how to deal with virtual envs is up in the air still. Either by supplying an optional executable property on the pip module, or using the virtualenv / virtualenv_command. I think one of them will be necessary and I don't know the answer to this yet because I use neither in production, so we would have to research it.

**Comment by nickjj** [comment]
This has been fully addressed in v1.6.0. Check the README file for details.

**Comment by sammervalgas** [comment]
I used the command bellow:

`pip install docker-compose --force-reinstall --user `

This solved my problem.
Tks.

**Comment by shoe-diamente** [comment]
I'm having this problem.
My playbook is this:

```yaml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
        # Reference: https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes 

    - name: Install Docker & Docker compose
      include_role:
        name: "nickjj.docker"
        apply:
          tags: 
            - docker

    - name: Install python packages for ansible
      apt:
        package:
        - python-apt
        - python-docker
        force_apt_get: yes 

    - name: Start services
      become: yes
      docker_compose:
        project_src: "{{ base_path }}"
        state: present
```

and I'm getting:

```
TASK [Start services] **********************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: Traceback (most recent call last):\n  File \"/tmp/ansible_docker_compose_payload_W_NWRI/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py\", line 477, in <module>\nImportError: No module named compose\n"}
```

Doesn't this role install docker as well as docker-compose?

**Comment by shoe-diamente** [comment]
If I add:

```yaml
     vars:
        ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
```

to the task like so:

```yaml
    - name: Start services
      become: yes
      docker_compose:
        project_src: "{{ base_path }}"
        state: present
      vars:
        ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
```

I get:

TASK [Start services] ***********************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ubuntu1804.localdomain's Python /usr/local/bin/python-docker. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}

**Comment by nickjj** [comment]
@shoe-diamente 

This role installs Docker and Docker Compose but it's not going to start your Docker Compose projects. Managing your applications after Docker and Docker Compose is installed is up to you.

You also don't need to apt install `python-apt` and `python-docker`.

The docs do mention under *"Working with Ansible's `docker_*` modules"*:

```yml
At either the inventory, playbook or task level you'll need to set
ansible_python_interpreter: "/usr/bin/env python-docker".
This works because this role symlinks the Virtualenv's Python binary to python-docker.
```

This is currently working when I use the `docker_login` module to optionally login to a registry in the role. By default this role pip installs docker and docker compose so that "docker" module should be available.

**Comment by shoe-diamente** [comment]
I've destroyed the VM. Removed the tasks that installed `python-apt` and `python-docker` and added:

```
      vars:
        ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
```

now it stops even before at a `docker_image` task:

```yaml
    - name: Load services
      become: yes
      docker_image:
        load_path: "{{ base_path }}/{{ item }}.tar"
        name: {{ item }}
        tag: latest
        source: load
      with_items:
        - database
        - server
        - client
      vars:
        ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
```

with:

```
failed: [vagrant] (item=database) => {"ansible_loop_var": "item", "changed": false, "item": "database", "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ubuntu1804.localdomain's Python /usr/local/bin/python-docker. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
```

**Comment by nickjj** [comment]
Did this role's pip tasks run to install those packages?

Did you try SSHing into the server and seeing if you can run `/usr/bin/env python-docker`?

**Comment by shoe-diamente** [comment]
> Did this role's pip tasks run to install those packages?

Currently the only packages installed are the ones from `ansible-docker`'s role. I've also attempted to run this task:

```
    - name: Pip install docker for Ansible's docker_* modules
      pip:
        name: 
          - docker
          - "docker-compose"
```

after `ansible-docker`'s role and before the failing task to no success (same error).

> Did you try SSHing into the server and seeing if you can run `/usr/bin/env python-docker`?

It seems like it can run that:

```
$ /usr/bin/env python-docker
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
