### ISSUE TITLE
Failing installation of dependencies on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by zbrox** [nickjj/ansible-docker#45]
When running a playbook that uses the role with the following settings:

```yaml
        docker__edition: "ce"
        docker__channel: "stable"
        docker__install_docker_compose: true
        docker__users: ["ubuntu"]
```

on a clean install of Ubuntu 18.04.1.

The error is the following:

`FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use.  pip needs to be installed."}`

However, when checking pip is installed and found at /usr/bin/pip.
