### ISSUE TITLE
Destination /etc/apt/preferences.d not writable

### ISSUE THREAD

**Issue by magick93** [nickjj/ansible-docker#56]
Hello

I'm getting the below error when I try to run the role using:

```
  - include_role:
      name: nickjj.docker
    become: true
    vars:
      docker__version: "18.09"
      docker__daemon_json: "{ \"insecure-registries\": [\"172.30.0.0/16\"] }"
```

```
TASK [nickjj.docker : Enable pinned Docker version] **********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "9e991811a558ae7ed14939f514a28e38044e58ca", "msg": "Destination /etc/apt/preferences.d not writable"}
```

# Version info

## OS

```
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

## Ansible

```
ansible 2.7.9
  config file = None
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

```

**Comment by nickjj** [comment]
Hi,

Does your playbook have `become: true` set? Check the example playbook in the README for details.

**Comment by magick93** [comment]
Yes, it does.

**Comment by magick93** [comment]
> Also, have you tried running it against Ubuntu 18.04? 19.04 isn't officially supported.

I havent tried on 18:04. But, as its a permissions error, I'd be surprised if the issue is any different.

**Comment by nickjj** [comment]
> I havent tried on 18:04. But, as its a permissions error, I'd be surprised if the issue is any different.

It's worth testing just to eliminate variables because I haven't ever heard of anyone else hitting this issue and I just used this role yesterday to install Docker on both an Ubuntu 18.04 and Debian Buster server and didn't run into this (or any) issues.

**Comment by nickjj** [comment]
I personally don't use the `include_role` pattern but try replacing:

```yml
  - include_role:
      name: nickjj.docker
    become: true
    vars:
      docker__version: "18.09"
      docker__daemon_json: "{ \"insecure-registries\": [\"172.30.0.0/16\"] }"
```

With this:

```yml
  - include_role:
      name: nickjj.docker
    vars:
      ansible_become: true
      docker__version: "18.09"
      docker__daemon_json: "{ \"insecure-registries\": [\"172.30.0.0/16\"] }"
```

That's based on: https://github.com/ansible/ansible/issues/29159#issuecomment-380862971

In other words, `become: true` isn't being set for the role with your above set up, which is why you're getting those permission errors.

You could also follow the README in this repo and make a new playbook called `docker.yml` and run it like this:

```yml
---

# docker.yml

- name: Example
  hosts: "all"
  become: true

  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```

**Comment by magick93** [comment]
Thanks

This solves the permissions issue:
```
  - include_role:
      name: nickjj.docker
    vars:
      ansible_become: true
      docker__version: "18.09"
      docker__daemon_json: "{ \"insecure-registries\": [\"172.30.0.0/16\"] }"
```
