### ISSUE TITLE
Running on Raspian

### ISSUE THREAD

**Issue by FauthD** [nickjj/ansible-docker#65]
Hi,
a few changes are required:
Host vars:
```
docker__apt_repository: >
  deb [arch=armhf]
  https://download.docker.com/linux/raspbian
  {{ ansible_distribution_release }} {{ docker__channel | join (' ') }}
```

And install_recommends: no
```
- name: Install Docker
  apt:
    name: "docker-{{ docker__edition }}"
    state: "{{ docker__state }}"
    install_recommends: no
```

Later it fails in "Install Python packages".
I saw some warnings about python 2 deprecation. But this is the error:
`ERROR: Failed building wheel for cryptography\nERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly`

Any ideas?

Edit: Solution see below.
