### ISSUE TITLE
No package matching 'docker-ce'

### ISSUE THREAD

**Issue by IoTPlay** [nickjj/ansible-docker#66]
Hi Nick, sorry to drop in, my 1st time I use your role, loading to RPi3B+ with Buster lite on it. Probably do not understand your instructions properly. Want to install CE. Have not configured my docker id anywhere. Used the Playbook example in your readme:
```
- name: Docker to Host
  hosts: "all"
  become: true

  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```
Roles before the one below installed, but the one below failed. Any pointers?
```
TASK [nickjj.docker : Install Docker] *********************************************************************************************
fatal: [rh02test]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}
```
