### ISSUE TITLE
No crontab for root

### ISSUE THREAD

**Issue by ggregoire** [nickjj/ansible-docker#67]
First of all, thanks for the role!

A question about the cron. I got it created without issue:

```
TASK [nickjj.docker : Create Docker related cron jobs] ***************************************************************
ok: [localhost] => (item={u'job': u'docker system prune -af > /dev/null 2>&1', u'cron_file': u'docker-disk-clean-up', u'user': u'root', u'name': u'Docker disk clean up', u'schedule': [u'0', u'0', u'*', u'*', u'0']})
```

But when I check the cron list with `crontab -l`, I get:

```
no crontab for root
```

How can I check if the cron is correctly installed?

---

For context here is the playbook:

```
---
- hosts: all
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```

Which I play in a debian 10 in docker. https://github.com/geerlingguy/docker-debian10-ansible

```
❯ docker exec --tty debian-ansible env TERM=xterm ansible-playbook /etc/ansible/playbooks/docker.yml

    ...

    TASK [nickjj.docker : Create Docker related cron jobs] ***************************************************************
ok: [localhost] => (item={u'job': u'docker system prune -af > /dev/null 2>&1', u'cron_file': u'docker-disk-clean-up', u'user': u'root', u'name': u'Docker disk clean up', u'schedule': [u'0', u'0', u'*', u'*', u'0']})

    ...

❯ docker exec -it debian-ansible bash

    root@0257f15480e0:/# crontab -l
    no crontab for root
```

**Comment by nickjj** [comment]
Hi,

The cron job is written out to disk at a specific path instead of being accessible with `crontab -l`.

Check out `/etc/cron.d/` on your server. You should see the cron job(s) there.

**Comment by ggregoire** [comment]
Indeed it's there, thanks!

**Comment by nickjj** [comment]
No problem. The reason for that stemmed from this issue: https://github.com/nickjj/ansible-docker/issues/35

**Comment by uchris13** [comment]
> The cron job is written out to disk at a specific path instead of being accessible with `crontab -l`.

I´d love to understand this. why to write it directly instead of doing it via Crontab? how do you manage it? what is the logic behind all this?

**Comment by nickjj** [comment]
It's more straight forward to be able to see a list of cron jobs on your system by going to a centralized place on your file system (`/etc/cron.d`) than wondering which cron jobs exist in each user's `crontab -l`. You can still run cron jobs as a non-root user with the `/etc/cron.d` approach since one of the arguments of the cron job is picking which user it runs as.

From an automation standpoint it's also easier to only have to think about adding and removing files in a directory instead of parsing a crontab file.

**Comment by uchris13** [comment]
So if i understood correctly by just dropping files into /etc.d/daily, weekly, monthly scripts will be executed. How do you specify the user and the time?

I'm still a bit confused

**Comment by nickjj** [comment]
Yes, they just need to exist in any of those directories and cron picks it up automatically. You don't need to restart anything.

My role does this by default:

```yml
docker__cron_jobs_prune_flags: "af"
docker__cron_jobs_prune_schedule: ["0", "0", "*", "*", "0"]
docker__cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{ docker__cron_jobs_prune_flags }} > /dev/null 2>&1"
    schedule: "{{ docker__cron_jobs_prune_schedule }}"
    cron_file: "docker-disk-clean-up"
    user: "{{ (docker__users | first) | d('root') }}"
```

You can override those variables as needed if you want to change things.

By default it runs the cron job every Sunday at midnight, that's what `["0", "0", "*", "*", "0"]` is, you can verify it here: https://crontab.guru/#0_0_*_*_0
