### ISSUE TITLE
Discard output of docker system prune

### ISSUE THREAD

**Issue by jardleex** [nickjj/ansible-docker#7]
Hi,

I'd request a change on the cronjob to prune unused docker data. We run this role on several servers and receive a mail each time the command get's executed via cron.
How's about this?

```
docker_cron_tasks:
  - job: docker system prune -f &>/dev/null
    name: "Docker clean up"
schedule: ["0", "0", "*", "*", "0"]
```

A more complex solution would be a switch allowing the role user to select a behaviour.

**Comment by nickjj** [comment]
Hi,

If you don't want to receive the email you can just override the default without modifying this role.

Just supply this in your inventory variables for the servers:

```yml
docker_cron_tasks:
  - job: docker system prune -f &>/dev/null
    name: "Docker clean up"
    schedule: ["0", "0", "*", "*", "0"]
```
