### ISSUE TITLE
elasticsearch discovery issue

### ISSUE THREAD

**Issue by eoli3n** [nickjj/ansible-docker#71]
Hi,
I use ELK on docker swarm.
When i install docker manually, the stack is working.
But when i use your role, ElasticSearch replicas fail to discover each other.
Is there anything you which could change default network behaviour when using swarm on top of your role ?

Here's what i use
```
---
- hosts: swarm_test:swarm_prod
  roles:
    # https://github.com/nickjj/ansible-docker
    - role: nickjj.docker
      tags: docker
      vars:
        docker__edition: "ce"
        docker__channel: ["stable"]
        docker__version: "19.03"
        docker__state: "present"
        docker__compose_version: ""
        # `a` removes unused images (useful in production).
        # `f` forces it to happen without prompting you to agree.
        docker__cron_jobs_prune_flags: "af"
        # Control the schedule of the docker system prune.
        docker__cron_jobs_prune_schedule: ["0", "0", "*", "*", "0"]
        docker__cron_jobs:
          - name: "Docker disk clean up"
            job: "docker system prune -{{ docker__cron_jobs_prune_flags }} > /dev/null 2>&1"
            schedule: "{{ docker__cron_jobs_prune_schedule }}"
            cron_file: "docker-disk-clean-up"
            #user: "{{ (docker__users | first) | d('root') }}"
            #state: "present"
        docker__pip_virtualenv: "/usr/local/lib/docker/virtualenv"
        docker__pip_docker_state: "present"
        docker__pip_docker_compose_state: "present"
  
   # https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html
    - role: docker.swarm
```

``docker.swarm`` role

```
---
- name: install docker pip dep
  apt:
    name: python-docker
    state: present

- name: Create swarm on manager node
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"
  register: swarm
  when: "'managers' in group_names"

- name: Gather network facts
  setup:
    gather_subset:
      - network

- name: debug managers
  debug:
    msg: "Join workers at {{ hostvars[groups['managers_test'][0]]['ansible_facts']['default_ipv4']['address'] }}:2377 with token {{ swarm['swarm_facts']['JoinTokens']['Worker'] }}"
  when: "'managers' in group_names"

- name: set facts token
  set_fact:
    token : "{{ swarm['swarm_facts']['JoinTokens']['Worker'] }}"
  when: "'managers' in group_names"

- name: Add other nodes to swarm_test
  docker_swarm:
    state: join 
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['managers_test'][0]]['token'] }}"
    remote_addrs:
      - "{{ hostvars[groups['managers_test'][0]]['ansible_facts']['default_ipv4']['address'] }}:2377"
  when: "'workers' in group_names"
```
