### ISSUE TITLE
Failed to import the required Python library

### ISSUE THREAD

**Issue by shoe-diamente** [nickjj/ansible-docker#74]
Given this vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "vagrant"

  config.vm.provision "deploy", type: 'ansible' do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/deploy.yml"
    ansible.groups = {
      "staging" => ["vagrant"]
    }
  end
end
```

and this playbook:

```yaml
- name: Deploy
  hosts: vagrant
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
        # Reference: https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes 

    - name: Install Docker & Docker compose
      include_role:
        name: "nickjj.docker"
        apply:
          become: yes
          tags: 
            - docker

    - name: Pip install docker for Ansible's docker_* modules
      pip:
        name: 
          - docker
          - "docker-compose"

    - name: Save services
      local_action:
        module: docker_image
        archive_path: /tmp/{{ item }}.tar
        build:
          path: ../{{ item }}
          pull: yes
        name: {{ item }}
        tag: latest
        force_source: yes
        source: build
      with_items:
        - database
        - server
        - client
        - documents

    - name: Upload services
      copy:
        src: /tmp/{{ item }}.tar
        dest: "{{ base_path }}/{{ item }}.tar"
      with_items:
        - database
        - server
        - client
        - documents

    - name: Load services
      become: yes
      docker_image:
        load_path: "{{ base_path }}/{{ item }}.tar"
        name: {{ item }}
        tag: latest
        source: load
      with_items:
        - database
        - server
        - client
        - documents
      vars:
        ansible_python_interpreter: "/usr/bin/env python-docker"
```

I get:

```
failed: [vagrant] (item=database) => {"ansible_loop_var": "item", "changed": false, "item": "database", "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ubuntu1804.localdomain's Python /usr/local/bin/python-docker. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
```

**Comment by shoe-diamente** [comment]
> Within that python prompt can you run import docker and import docker_compose without getting an error?

It says "module not found" when I try `import docker`.

**Comment by nickjj** [comment]
What happens if you set up a `docker.yml` playbook (check the README) and run that before you run your custom tasks in another playbook?

**Comment by shoe-diamente** [comment]
@nickjj So a playbook `docker.yml` with the first two tasks of this one (`Update and upgrade apt packages` and `Install Docker & Docker compose`) right?

**Comment by nickjj** [comment]
No, just the update / upgrade apt task. The other task is something this role already does for you. You don't need to define that.

**Comment by shoe-diamente** [comment]
I've run the following `docker.yml`:

```yaml
- name: Deploy
  hosts: vagrant
  become: yes
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
        # Reference: https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes 
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```

then I tried to run `/usr/bin/env python-docker` and inside the interpreter `import docker` but I get:

```
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'docker'
```

**Comment by nickjj** [comment]
If I spin up a Vagrant box using https://app.vagrantup.com/bento/boxes/ubuntu-18.04 and run the role along with running `sudo apt-get update && apt-get install -y python` beforehand (to bootstrap Ansible), I'm able to SSH in, run `/usr/bin/env python-docker` and successfully run `import docker` without errors.

**Comment by shoe-diamente** [comment]
@nickjj This is p confusing.
Can you please try with this vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "vagrant"

  config.vm.provision "deploy", type: 'ansible' do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/docker.yml"
    ansible.groups = {
      "staging" => ["vagrant"]
    }
  end
end
```

and with the above playbook named as `ansible/docker.yml` and then run `vagrant up`?

**Comment by nickjj** [comment]
Can you try it without using the built in ansible features of vagrant? Those don't really resemble a production environment and I don't know what crazy things vagrant does behind the scenes.

You should spin up a brand new server without any extra vagrant provision steps and then:

1. Install python on the server

2. Create and configure some type of non-root user to SSH in as

3. Configure this Docker role to use that user you just created

4. Run the docker playbook

That is what I'm doing here. Running Ansible against a vagrant VM should be no different than how you would against a production server and the above steps work in both environments.

**Comment by shoe-diamente** [comment]
Ok, I've removed the provision configuration in the vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "vagrant"
end
```

I've added the host explicitly in my vagrant file:

```yaml
all:
  children:
    staging:
      hosts:
        vagrant:
          ansible_host: localhost
          ansible_user: vagrant
          ansible_port: 2222
          ansible_ssh_common_args: -i .vagrant/machines/vagrant/virtualbox/private_key
```

then I've run the playbook:

```yaml
- name: Deploy
  hosts: vagrant
  become: yes
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
        # Reference: https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes 
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```

nothing changed. Everything happened exactly as if I was setting up provisioning with Vagrant.

With regards to the non-root to SSH to, is this user already created by the role?
How do I configure this ansible-docker role to use that user instead?

**Comment by nickjj** [comment]
This role doesn't create the user. That is a system level decision unrelated to using Docker.

Check the readme at: https://github.com/nickjj/ansible-docker#configuring-users-to-run-docker-without-root

You might be able to get away with using the vagrant user without having to make a new user. In that case, setting `docker__users: ["vagrant"]` might do it.

**Comment by shoe-diamente** [comment]
I've modified my playbook with what you suggested:

```yaml
- name: Deploy
  hosts: vagrant
  become: yes
  vars:                                             # NEW
    docker__users: ["vagrant"]      # NEW
  pre_tasks:
    ...
```

but I'm still unable to `import docker` inside `/usr/bin/env python-docker`.

**Comment by nickjj** [comment]
What is the exact playbook and vagrantfile you're using now? I will try to set it up tonight and test it.

**Comment by shoe-diamente** [comment]
Playbook:

```yaml
- name: Deploy
  hosts: vagrant
  become: yes
  vars:
    docker__users: ["vagrant"]
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
        # Reference: https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes

    - name: Install python
      apt:
        name:
          - python
        state: present
        
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
```

Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "vagrant"
end
```

Inventory file:

```yaml
all:
  children:
    staging:
      hosts:
        vagrant:
          ansible_host: localhost
          ansible_user: vagrant
          ansible_port: 2222
          ansible_ssh_common_args: -i .vagrant/machines/vagrant/virtualbox/private_key
```

Thank you by the way. 😊
