### ISSUE TITLE
variables not written to daemon.json

### ISSUE THREAD

**Issue by zerr0s** [nickjj/ansible-docker#79]
Hi,

I'm trying to setup docker with custom daemon options, but when ansible write the file, there is just the default opton written in it. The cron job is written to for root, and the user is not added to docker group.

I don't understand what i am doing wrong ?

```
### Begin nickjj.docker ###
docker__edition: "ce"
docker__channel: ["stable"]
docker__version: ""
docker__state: "present"
docker__users: ["generic"]

docker__daemon_json: |
  "bip": "172.1.1.0/24"
  "data-root": "/data/docker"
  "log-driver": "journald"
  "storage-driver": "overlay2"
  "log-opts": { "max-size": "10m", "max-file":"5" }
  "hosts": [ "unix:///var/run/docker.sock", "tcp://0.0.0.0:2375" ]
docker__cron_jobs_prune_flags: "af"
docker__cron_jobs_prune_schedule: ["0", "0", "*", "*", "0"]
docker__cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{ docker__cron_jobs_prune_flags }} > /dev/null 2>&1"
    schedule: "{{ docker__cron_jobs_prune_schedule }}"
    cron_file: "docker-disk-clean-up"
    user: "generic"
    state: "present"
### End nickjj.docker ###
```

Thanks.
