### ISSUE TITLE
v2.0.0 Failed on ubuntu 18.04

### ISSUE THREAD

**Issue by debonzi** [nickjj/ansible-docker#89]
Using with the .yml
```yml
---
- name: Docker Server
  hosts: "all"
  become: true
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
``` 

I got the result:
```
$ ansible-playbook sciencedesk-docker.yml 

PLAY [Docker Server] ****************************************************************

TASK [Gathering Facts] ************************************
ok: [sandbox.sciencedesk.net]

TASK [nickjj.docker : Disable pinned Docker version] ***************************************************************
ok: [sandbox.sciencedesk.net]

TASK [nickjj.docker : Enable pinned Docker version] ***************************************************************
skipping: [sandbox.sciencedesk.net]

TASK [nickjj.docker : Install Docker's dependencies] ***************************************************************
fatal: [sandbox.sciencedesk.net]: FAILED! => {"changed": false, "msg": "No package matching 'gnupg2' is available"}

PLAY RECAP ***************************************************************
sandbox.sciencedesk.net    : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0  
```
